###########################################################################################
# Pontificia Universidad Javeriana
# Autor: Alejandro Lopez Beltran
# Fecha: 11/10/2025
# Profesor: John Corredor
# Materia: Sistemas Operativos
# Tema: Sistemas de FIcheros
# Descripción: Automatizacion de compilacion de ficheros del laboratrio Sistema de Fichero
##########################################################################################


GCC = gcc


FLAGS=
MODULO =

PROGRAMAS = laboratorio01 laboratorio02

laboratorio01:
        $(GCC) $@.c -o $@ $(FLAGS)

laboratorio02:
	$(GCC) $@.c -o $@ $(FLAGS)

clean:
        $(RM) $(PROGRAMAS)
